### ISSUE TITLE
Compile error due to wrong override in Main.java

### ISSUE THREAD

**Issue by meyerhoefer-heitec** [paulc4/mvc-exceptions#1]
Hi,

trying to compile the demo app I get the following error:

[ERROR] return type void is not compatible with org.springframework.boot.builder.SpringApplicationBuilder

Seems that protected void configure(SpringApplicationBuilder application)  in Main.java is wrong and should be declared as 
protected SpringApplicationBuilder configure(SpringApplicationBuilder application) instead?

Or did the interface of SpringApplicationBuilder change recently and I just have a wrong superclass?

Best regards

Marcus

**Comment by paulc4** [comment]
This method now returns `SpringApplicationBuilder` - code was modified when I upgraded some time ago: https://github.com/paulc4/mvc-exceptions/commit/c01c3679f9e9dc9bdb0c39ad63a5871f6f52e702#diff-1e116c36417b98e3622eade6bca4aaf6

Closing this issue.
