### ISSUE TITLE
Compilation issue, surefire plugin version missing, no examples of handling filter related exceptions

### ISSUE THREAD

**Issue by krishna81m** [paulc4/mvc-exceptions#2]
This is not an issue, but it would be nice if you had at least ONE example of how to handle exceptions that propagate at filter level, all of the examples defined here only discuss handling exceptions originating from controllers. Other components especially filters, example: Spring security related filters, often throw exceptions that are not caught by these handlers. Could you post few examples/best practices on how to catch filter exceptions and return appropriate content type messages?

Besides this there is a compilation issue in Main class and one of the surefire plugins is missing in default repo, had to manually install this plugin.
[ERROR] Plugin org.apache.maven.plugins:maven-surefire-plugin:2.15 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:2.15: The repository system is ...
...
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: The repository system is offline but the artifact org.apache.maven.plugins:maven-surefire-plugin:pom:2.15 is not available in the local repository.
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)

**Comment by paulc4** [comment]
Spring Boot sets up its "Whitelabel" error page as the default error-page for the container.  So any exception thrown outside of Spring MVC, such as in a Filter, will still be reported in the same way.

I will add an example to the demo application - thanks.

**Comment by paulc4** [comment]
Example added to application - see `BrokenFilter` class.
