### ISSUE TITLE
Unnecessary (and slightly confusing) import in demo 2?

### ISSUE THREAD

**Issue by fivedogit** [paulc4/mvc-exceptions#4]
I'm not sure this line should appear in your demo2 GlobalExceptionHandlingControllerAdvice class.

import demo1.web.ExceptionHandlingController;

But I'm new to this stuff. I could be missing something.

**Comment by paulc4** [comment]
It is only there for the Javadoc (on the class comment, immediately below).

Sorry I missed replying to this for so long.
